---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/main/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.ts
#
server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: ${ELASTICSEARCH_HOSTS}

monitoring.ui.container.elasticsearch.enabled: true

## Security credentials
#
elasticsearch.username: kibana_system
elasticsearch.password: ${KIBANA_PASSWORD}

## Encryption keys (optional but highly recommended)
##
## Generate with either
##  $ docker compose up kibana-genkeys
##  $ openssl rand -hex 32
##
## https://www.elastic.co/docs/deploy-manage/security/self-setup
## https://www.elastic.co/docs/reference/kibana/commands/kibana-encryption-keys
#
xpack.security.encryptionKey: ${ENCRYPTION_KEY}
xpack.encryptedSavedObjects.encryptionKey: ${ENCRYPTION_KEY}
xpack.reporting.encryptionKey: ${ENCRYPTION_KEY}
